### ISSUE TITLE
Create adapter for Google Sheets as an IdStore

### ISSUE THREAD

**Issue by fillup** [silinternational/idp-id-sync#30]
For small standalone IdPs without a personnel system to integrate with, we can use simple Google Sheet to maintain user identities and sync from it.

**Comment by forevermatt** [comment]
Assuming that ssp-base will successfully build once it's set to include the latest updates to idp-id-sync, I think this is done. I don't know whether we'll have to update all the various Idp-in-a-Box `composer.json` files to use the newer version of `PhpEnv` (since it had a backwards breaking change at some point recently) before ssp-base will build, though.

**Comment by forevermatt** [comment]
Finished in 3584766.
